# Generated by Django 5.2.5 on 2025-08-30 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Credit')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Debit')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='SpendAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eb_bill', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='EB Bill')),
                ('gas_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('groceries', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Groceries / Home Items')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost.profile')),
            ],
        ),
    ]
